# Generated by Django 3.2.2 on 2021-05-09 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_advisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.advisor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.myuser')),
            ],
        ),
    ]
